### PR TITLE
Get opts.auth working with XMLHttpRequest in http-pouchdb

### PR DESCRIPTION
**Pull request by hiddentao**
This ensures that the `api.allDbs` call makes use of the `opts.auth` setting, if provided.

Please let me know if you'd like a more thorough unit test which actually checks the `Authorization` header value.

### CODE REVIEW

**Comment by hiddentao** [comment]
@marten-de-vries I've rebased, thanks!

**Comment by marten-de-vries** [comment]
@hiddentao Great! It seems like Travis fails because of a simple dependency issue, which should be an easy fix. (I'm checking its correctness in https://github.com/pouchdb/pouchdb-server/pull/334). Closing this in favour of that PR.

**Comment by marten-de-vries** [comment]
Merged: 4e34f15f5e19c02532bf16c94e6a22e41997c129

Thanks @hiddentao!

**Comment by hiddentao** [comment]
Thanks.

**Pull request closed without merging**
