### PR TITLE
(#115) - rename --no-stdout-logs to --silent

### PR DESCRIPTION
**Pull request by marten-de-vries**
This is a breaking change.

### CODE REVIEW

**Comment by nolanlawson** [comment]
I'd prefer not to do this and to work around it somehow, since there are actually quite a few places now where we are running `pouchdb-server` with `-n` (including pouchdb-server, express-pouchdb, and pouchdb). Isn't there any way to work around this and avoid the major version bump?

**Comment by nolanlawson** [comment]
BTW tests are failing because express-pouchdb needs a new version to fix the Firefox bug.

**Comment by marten-de-vries** [comment]
Ok, how about this. --no-stdout-logs has never worked, so technically we can't break it. So we can rename the long option to --silent, but keep the old couchName (no-stdout-logs) and -n short option. If that's ok with you I can update the PR.

**Comment by nolanlawson** [comment]
OK, that works for me!

**Comment by marten-de-vries** [comment]
Ok, this should do the trick. Waiting for Travis...

**Comment by nolanlawson** [comment]
Travis is beyond busted. I'm working on unbreaking express-pouchdb, but there are a lot of bugs.

**Comment by nolanlawson** [comment]
rebased

**Comment by nolanlawson** [comment]
On second thought, I think it's way too confusing to add a new option that's exactly the same as the old option, just because we can't figure out how to get `yargs` to do what we want it to do.

Let's please rewrite this so the option actually works. Last time I looked at this, it seemed like there were workarounds for `yargs` that we can use. Let's keep the mental overhead for our users to a minimum.

**Pull request closed without merging**
