### PR TITLE
Monorepo

### PR DESCRIPTION
**Pull request by garrensmith**
Create a monrepo for all the PouchDB server packages.

### CODE REVIEW

**Comment by garrensmith** [comment]
This is the start of the monorepo for PouchDB-server. So far the pouchdb-server and express tests pass. I have some questions before I can continue:

* Do I need to add any other packages?
* Do I need to remove any packages?
* Some of the packages have unit tests, should I leave those tests in each package and run them from there or group them into one large tests folder? I would prefer to leave them in their associated package.
* What am I missing in terms of making this a monorepo? Is it setup correctly, anything else I can do to make this better?
* I haven't been able to add in the commit history of the other packages. Should we add everyone thats commited to those packages as contributors in the package.json? 
* In PouchDB each package.json says `5.5.0-prerelease` how do you get Lerna to update each package.json like that?

**Comment by nolanlawson** [comment]
> In PouchDB each package.json says 5.5.0-prerelease how do you get Lerna to update each package.json like that?

I had to write [a manual script](https://github.com/pouchdb/pouchdb/blob/fd87966360320495b0c504d208816d61a7f4051f/bin/set-version.js) to do that, unfortunately.

**Comment by nolanlawson** [comment]
Everything in your PR looks correct to me. A few comments:

1. Running all tests at the top level is probably easiest. Stuff like `require('./packages/foo')` is what I did in Pouch. I would move all tests to the top and then write one single `npm test` script to test them.
2. Having individual build scripts for each package is fine, and indeed it's the "recommended" way to run Lerna, but for the PouchDB build I found it too slow, so I wrote one top-level build script that runs in a single Node.js instance (less startup time for each build). You can do it either way; it depends on whether you think the build takes too long or not.
3. independent=false is the easiest option I found with Lerna, although supposedly they have a good system for updating versions incrementally, but I couldn't really figure it out.

**Comment by garrensmith** [comment]
pinging @marten-de-vries because  he has written to many of these packages. I would love your opinion.

**Comment by garrensmith** [comment]
Also notifying @yaronyg

**Comment by yaronyg** [comment]
Wow! For https://github.com/pouchdb/express-pouchdb/pull/329 should I try to sneak it in before this lands or just wait until after? Just let me know, I want to add value not create problems so I'm happy to submit either before or after.

**Comment by yaronyg** [comment]
Note: I won't be submitting 329 exactly, I'll submit a new PR with just the single file I need changed. So I'm referring to a new PR. Should I hold off until after the mono-repo lands or do it now?

**Comment by garrensmith** [comment]
I don't think it will matter. If you do it know we just won't get the commit history. 

Otherwise you can even commit it against the monorepo. The main tests are already working. 

All misspelling thanks to my iPhone

**Comment by yaronyg** [comment]
I'm going to go with the monorepo. Might as well live in the future!

**Comment by garrensmith** [comment]
Haha. That would be great. Also nice to have someone else test it. Let me know if anything isn't clear. 

All misspelling thanks to my iPhone.




On Thu, Jul 7, 2016 at 7:23 PM +0200, "Yaron Y Goland" <notifications@github.com> wrote:












I'm going to go with the monorepo. Might as well live in the future!

**Comment by yaronyg** [comment]
I have an early 2015 Macbook Pro and the build process has had my machine pegged for over 10 minutes. Yikes! 

I then ran the tests and they immediately failed because leveldown isn't installed (e.g. https://github.com/pouchdb/pouchdb/issues/5257 which @nolanlawson and @daleharvey can't repo). I'm using Node.js 4.4.7 which is LTS and should be our baseline. I'm using npm 3.10.3.

I'm digging through the scripts now to figure out where I will have to manually install leveldown to make things work.

**Comment by garrensmith** [comment]
Could you try with Node 6 and see if it works then. I was using Node 6 and so was Travis. This will at least help eliminate causes of the issue. Are you using Lerna 2.0 beta?

All misspelling thanks to my iPhone

**Comment by yaronyg** [comment]
Yup, everything runs on node 6. So we should probably put up a warning that devs wants to run our tests should have at least node 5 (which is what I believe @nolanlawson and @daleharvey are using).

Note that I did have a test fail.

```

  1)  "after each" hook for "#3136 style=all_docs with conflicts":
     Error: ETIMEDOUT
      at onError (packages/pouchdb/lib/index.js:5154:18)
      at Request._callback (packages/pouchdb/lib/index.js:5196:14)
      at self.callback (packages/pouchdb/node_modules/request/request.js:200:22)
      at Timeout._onTimeout (packages/pouchdb/node_modules/request/request.js:775:12)
```

**Comment by garrensmith** [comment]
Ok great. That is helpful. A warning is a great idea. The tests are a little flaky. I have seen some timeout issues. After monorepo I would like to see if I can fix that. 

All misspelling thanks to my iPhone

**Comment by yaronyg** [comment]
Well, I wonder if this isn't https://github.com/pouchdb/express-pouchdb/issues/328 aka https://github.com/pouchdb/pouchdb/issues/5114 which I do have a fix for. So I can throw that in with https://github.com/pouchdb/express-pouchdb/pull/329

**Comment by garrensmith** [comment]
Possibly. I haven't dived into the tests enough yet. But if you can fix it
as well, that would be great.

**Comment by yaronyg** [comment]
@garrensmith As a side note I ran the pouchdb-server 'npm test' but pointed at the PR I just submitted to PouchDB (which also includes the PR I submitted yesterday that is now in master) instead of PouchDB/Master and it's the first time, ever, that I got all the tests in pouchdb-server to pass all the way to the end! So I'm hoping this means I really did nail that ETIMEDOUT problem.

**Comment by garrensmith** [comment]
Wow thats great news. If you can get all the tests to pass repeatedly on Travis without a timeout failure then I think you have fixed the issue. I'll try and continue with this work later this week.

**Comment by yaronyg** [comment]
@garrensmith , 
    @daleharvey accepted the PR that I think fixed ETIMEDOUT into master so given that we run tests using the latest version from Master (rather than what is published in NPM) then we should be good in terms of trying it out in Travis. Any idea on what the plan is to merge this PR? I ask because our tests are blocked on #144 and I'd rather not set up a custome install and build for that branch. I'd rather just use express-pouchdb from NPM. Thoughts?

**Comment by marten-de-vries** [comment]
This looks great! Some answers from me:

>    Do I need to add any other packages?

Probably, there are a couple of helper packages that are not directly used by express-pouchdb, but that do large amounts of work for packages you did include. The most important ones are:

- couchdb-eval
- couchdb-objects
- couchdb-render
- couchdb-resp-completer
- pouchdb-system-db

The next ones are standing a bit more on their own, but are still all used. If a bug is found in pouchdb-server, they might still very well be the cause, so integrating them probably makes sense:

- pouchdb-bulkdocs-wrapper
- pouchdb-changeslike-wrapper
- pouchdb-req-http-query
- pouchdb-route

Then there are a couple of general plugin packages they make use of, but that can completely stand on their own. Not sure what to do about those. I'm fine with them going either way:

- header-case-normalizer
- promise-nodify
- pouchdb-plugin-error
- pouchdb-plugin-helper (used by most of the unit tests for the plugins)

Oh, and finally, maybe pouchdb-all-dbs?

> Do I need to remove any packages?

Not as far as I can see.

> Some of the packages have unit tests, should I leave those tests in each package and run them from there or group them into one large tests folder? I would prefer to leave them in their associated package.

I agree, those tests are all highly specific to the APIs specified by their own packages. Putting them on a centralized pile only makes it hard to distinguish what is being tested, without any gain. Centralizing the test runner might still be possible and make sense. (The tests already all use the same test runners etc., using pouchdb-plugin-helper.)

> What am I missing in terms of making this a monorepo? Is it setup correctly, anything else I can do to make this better?

The plugins currently have some extra functionality that might be worth integrating centrally, to make development easier later on. E.g. IIRC they all currently check test coverage (and at 100%). There's also linters (both for ES5 and ES6 code), and browserify commands for making browser builds. But that's not as important as getting the unit tests to run in my opinion.

> I haven't been able to add in the commit history of the other packages. Should we add everyone thats commited to those packages as contributors in the package.json?

Fine with me, but putting 'PouchDB contributors' in there would work for me as well.

**Comment by garrensmith** [comment]
Thanks @marten-de-vries that is really helpful. I'll look at adding some of those other packages. I think we can also add some of those packages incrementally as we go. So I might look at getting a nice framework working here. And then we can add more and more packages to this as we go.

Going forward with this PR. I think the following steps are required before we can merge:

1. Add all required packages
2. Get all the unit tests up and running
3. Move from jshint -> eslint (I will probably look at a few codemods to help with this)
4. Merge

@yaronyg I would prefer that we only run the tests again a release PouchDB version. I spent a lot of time last week seeing why the pouchdb-server tests failed and it was because there was changes in PouchDB released version and the tests on master. Sticking to the release PouchDB makes this easier.

**Comment by marten-de-vries** [comment]
@garrensmith Agreed, no need to at them all now. Just pointing out the eventual goal. Let's get the current set merged first - although preferably with their tests running.

Using a released version of PouchDB is probably ok at the moment - that might change if someone at some point wants to improve couchdb-harness compatibility at some point, my experience is that that pretty quickly leads to modifications (of edge cases) in PouchDB itself. But let's not go there until it becomes necessary.

**Comment by garrensmith** [comment]
A quick update on this. I've moved all the tests to `test` folder. This means we can have one test runner. I was a little nervous to do this but I think its worked out well. All the unit tests are running. Just one test is failing. 

I've also integrated eslint and fixed all linting issues. I think once the unit tests are working we pretty close to done for a first version. 

I have added Nolan, Martin and myself to the contributors list. Who else should I add?
Finally what should I put in the readme's for each package?

The current packages in this repo are:

* express-pouchdb
* pouchdb-all-dbs
* pouchdb-auth
* pouchdb-list
* pouchdb-replicator
* pouchdb-rewrite
* pouchdb-route
* pouchdb-security
* pouchdb-server
* pouchdb-show
* pouchdb-size
* pouchdb-update
* pouchdb-validation
* pouchdb-vhost
* pouchdb-wrappers

**Comment by garrensmith** [comment]
Things left to do:

[] Clean out package.json for each repo (remove devDependencies)
[] Built step for each plugin
[] Update all readme's
[] Get access to all npm repo's for publishing

**Comment by nolanlawson** [comment]
I would just put stub READMEs inside each sub package linking back to this repo. You can write a short sentence about each one, but it's not terribly important. Maybe copy over the READMEs from Martin's original packages?

As for the contributor list, it's fine, since it doesn't affect npm's behavior at all. For the PouchDB sub-packages I just put Dale in there. :)

**Comment by garrensmith** [comment]
Ok a quick update on this. I've added some info in the README's. 
This is almost ready to go. The major issue is that we have two failing unit tests. I haven't had a chance to dive in much. The tests pass when using CouchDB but fail with PouchDB-Server.

Once those tests are passing, we then need to wait for the next PouchDB release and we can then get some of the new PouchDB fixes which should help @yaronyg with some of his issues. 

Then we can release.

**Comment by garrensmith** [comment]
If someone could help with the failing tests that would be awesome.

**Comment by yaronyg** [comment]
I'm happy to investigate but right now I have a dev who is literally blocked on me (on [this bug](https://github.com/thaliproject/Thali_CordovaPlugin/issues/812)). Once I get that cleared I can jump in and investigate.

I'm also working on getting some more folks up to speed on PouchDB and Express-PouchDB so that I'm not the only person on my team who can handle this kind of stuff.

**Comment by marten-de-vries** [comment]
Sorry, no time to check out & debug myself, but based on the output of the 2 unit tests that fail (from pouchdb-auth & pouchdb-show), it seems like there's a problem with the HTTP setup of the CouchDB instance (related to authentication cookies).

I see it's actually running the unit tests against pouchdb-server here. That was never CI tested, which is probably why it fails (still a bug, though). The easiest fix is probably to spin up a couchdb 1.x instance in Travis, and use that to run the unit tests against:
```
services:
  - couchdb
```

Arguably, that's also more valuable than running them against pouchdb-server: that way, the implementation of auth, show, update, validate, etc. isn't shared between the server and the client, preventing it from agreeing on faulty behaviour.

**Comment by garrensmith** [comment]
I think ideally we should run the tests against PouchDB-Server and CouchDB.
That is a nice way of making sure we support both.

**Comment by nolanlawson** [comment]
Monorepo work has stalled; I would rather continue with the status quo as opposed to create confusion about where the true repo is. For now let's just use separate repos unless we can do this monorepo rewrite all at once and quickly to avoid breakages, thanks

**Comment by garrensmith** [comment]
Yes that makes sense. Sorry that I got no further. 

All misspelling thanks to my iPhone.




On Fri, Dec 2, 2016 at 12:40 PM +0200, "Nolan Lawson" <notifications@github.com> wrote:












Closed #143.

**Comment by yaronyg** [comment]
And @garrensmith, I just wanted to say thanks for trying. Believe me when I say that I can fully empathize with a schedule that just won't let go and prevents you from finishing things up. But even just by starting the work you had the potential for planting a seed that others (like me if I wasn't drowning so badly) could have continued to nurture. So I really appreciate the effort.

**Pull request closed without merging**
