### PR TITLE
(#191) - avoid negative values in _changes limit param

### PR DESCRIPTION
**Pull request by shockry**

### CODE REVIEW

**Comment by gr2m** [comment]
I restarted the build earlier, still failing. The problem seems legit:
https://travis-ci.org/pouchdb/pouchdb-server/jobs/203278304

**Comment by nolanlawson** [comment]
That's really weird. In that case, we'll have to debug and investigate.

**Comment by nolanlawson** [comment]
I don't believe it's related to this PR. Also failing in master: https://travis-ci.org/pouchdb/pouchdb-server/builds/203312544

**Comment by gr2m** [comment]
In that case I suggest we merge this in and create a separate issue for the failing build?

**Comment by nolanlawson** [comment]
Good idea; we might as well just merge now and fix the build later. :+1:

**Pull request merged**
