### PR TITLE
(pouchdb/express-pouchdb#279) - silence logs in travis

### PR DESCRIPTION
**Pull request by nolanlawson**
This will probably fix the build once https://github.com/pouchdb/express-pouchdb/pull/280 is merged.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
:+1: when green & https://github.com/pouchdb/express-pouchdb/pull/280 is merged.

**Comment by nolanlawson** [comment]
Still working on it. express-pouchdb is green, but this repo is still red somehow.

**Comment by nolanlawson** [comment]
Yay, green!

**Comment by nolanlawson** [comment]
93d58869470be254e80d8c6f09fb6d7c7cccb19f

**Pull request closed without merging**
