### PR TITLE
(#326) endless polling

### PR DESCRIPTION
**Pull request by yaronyg**
I got this confused with another bug I was working on and so marked the commit with 5114 when it was supposed to be 326.

### CODE REVIEW

**Comment by yaronyg** [comment]
@garrensmith I should point out that while this does pass all the tests it only did so when I pointed it at https://github.com/pouchdb/pouchdb/pull/5457 which appears to take care of the ETIMEDOUT failures I would randomly get on various tests. And as discussed in #326 we need to decide what (if any) testing we want for this feature. As I discuss there at some length, there isn't an obvious way to test this unless we want to extract the code to a different file and add a new test just for that file.

**Comment by nolanlawson** [comment]
Unfortunately it looks like the monorepo work has stalled, so this should probably be moved to express-pouchdb repo for now.

**Comment by nolanlawson** [comment]
This appears related and yet incompatible with https://github.com/pouchdb/express-pouchdb/pull/403 so it would need more work to be in a state to merge. Sorry for the delay on this; this repo has been a mess for at least a year or more.

**Comment by yaronyg** [comment]
Understood. I'll clean this up when I finally get a chance to breath.

**Pull request closed without merging**
