### PR TITLE
Use process.env.port or 5984 as default port

### PR DESCRIPTION
**Pull request by bkniffler**
Makes it compatible to most hosting like heroku, dokku, etc

### CODE REVIEW

**Comment by nolanlawson** [comment]
The failure is due to a failure in Travis. In general, though, I'm uneasy about the idea of inserting weird behavior based on proprietary environment variables into the source code, when this could also be solved with something like

```
pouchdb-server -p ${port}
```

instead.

To me, this seems like something that should be fixed by a README update rather than a change to the code. Could you please add a note to the README instead? (Since I'm not sure what the exact syntax is for Heroku.)

**Comment by bkniffler** [comment]
Hm, this is not a weird, proprietary behaviour, this is the current convention. 
All hosting providers I know use process.env.port (azure, heroku, dokku via digitalocean, ..) and only process.env.port. It is simply not possible to deploy an app without using that process.env.port as you won't get to define command line args.
And look at popular frameworks, they either have process.env.port or they expect the port to be handed over programmatically (as a config object) if embedded into an app, so you can hand over process.env.port.
https://github.com/balderdashy/sails/blob/f9db888a4fd39d43138bad4b279ad86046c27482/lib/app/configuration/load.js#L133
https://github.com/wistityhq/strapi/blob/5e2ac2f95372e70f549040fc1cb46979acb28de0/lib/configuration/index.js#L56

You rely on automagically reading a static config.json file or having a command line argument, both ways are unflexible/undynamic  not runtime managable.
 
This really is an issue and there is literally zero reasons this shouldn't be implemented, there is no drawback, no risks, nothing. Your argument doesn't the solve the root problem.

**Comment by nolanlawson** [comment]
Thank you for the explanation; I didn't realize that it was impossible any other way, and that lots of *aaS providers were using this format. OK, I'm fine with this PR, but could we maybe also add a note to the README explaining that you can do:

```
port=9000 pouchdb-server
```

**Comment by nolanlawson** [comment]
merged as e7fa2de3c8de6777998b7ad08d6154f475029e87, added a note to the README about the auto-port feature

**Pull request closed without merging**
