### PR TITLE
pouchdb-vhost

### PR DESCRIPTION
**Pull request by gr2m**
part of #197

### CODE REVIEW

**Comment by gr2m** [comment]
unit tests are failing in very weird ways :/ reminds me of https://github.com/pouchdb/express-pouchdb/pull/356. I investigated a bit but couldn’t find the cause. I could work around the `.hasOwnProperty` bug but then others showed up and this is very hard to debug

**Comment by garrensmith** [comment]
I've seen this issue before. The tests will probably pass against CouchDB. I'm not quite sure how to fix it though.

**Comment by gr2m** [comment]
the same tests fails on the https://github.com/pouchdb/pouchdb-vhost repository when tests are run in Node 6. I couldn’t event get them to run in 4 or 0.10 which is the version it’s currently set to run on Travis. 

So I suggest we skip the failing tests and I create a follow up issue to figure out what is wrong

**Comment by marten-de-vries** [comment]
Closing (#250)

**Pull request closed without merging**
