### PR TITLE
Modernize and fix with recent versions of PouchDB.

### PR DESCRIPTION
**Pull request by loic**

### CODE REVIEW

**Comment by marten-de-vries** [comment]
I just restarted the failing tests for the third time to be sure, but I think the failures might actually be genuine.

**Comment by marten-de-vries** [comment]
Nice work. I looked into why ``test-express-minimum`` fails, as it surprised me, and I think it's just a mistake in the test suite implementation:

- The test that fails tries to cop out if it's not running in a fully fledged CouchDB (with validation etc.): https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.bulk_docs.js#L402
- express-pouchdb _in the minimum mode_ is not a fully fledged CouchDB, but the function the test suite uses to check for that thinks it is: https://github.com/pouchdb/pouchdb/blob/master/tests/integration/utils.js

**Comment by loic** [comment]
I'm really puzzled by those `test-express-minimum` failure,s the test suite fails in really weird ways.

First things start to go sour after a timeout, but since the timeout is always reproducible and doesn't seem time dependent (I tried to vary the timeout duration) I guess it's due to a deadlock.

Second, the test suite can't recover from that failure: I modify `test-node.sh` to remove the `--bail` option of mocha, by as soon as this failure happen mocha aborts.

I commented this failing `test.bulk_docs.js` test, and another test fails with a timeout in `test.replication.js`, and that's where things become hard to conceive. Commenting that new failing test makes the test immediately before it fail even though it was passing previously. Commenting that new failing test as well makes the one even before that fail, I've commented half a dozen tests before giving up. I'm having a hard time understanding how commenting a test makes a test that executes before it fail... I'm suspecting it may have sometime to do with `beforeEach`/`afterEach` routines.

Commenting the whole `test.replication.js` as well as the one failing test in `test.bulk_docs.js`, leads to 2 other failing tests, but at least those looks like more reasonable failures:

```
  1) test.sync.js-local-http #3270 triggers "denied" events:

      AssertionError: expected 0 to equal 2
      + expected - actual

      -0
      +2

      at tests/integration/test.sync.js:650:38
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  2) test.sync.js-local-http #3270 triggers "denied" events, reverse direction:

      AssertionError: expected 0 to equal 2
      + expected - actual

      -0
      +2

      at tests/integration/test.sync.js:696:40
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by loic** [comment]
There seems to be some similarities between `beforeEach`/`afterEach` of [test.bulk_docs.js](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.bulk_docs.js#L28-L34) and [test.replication.js](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L21-L28) that are specific to those 2 files: usage of `testUtils.adapterUrl` and `testUtils.cleanup`.

And it seems to be related to the `http` adaptor one way or another because if I comment the first 3 lines of https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.replication.js#L3-L8, then the test suite passes.

**Comment by loic** [comment]
Regarding the CouchDB `bulk_docs.js` deadlock: https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.bulk_docs.js#L453 should be `.then(done, done)` so the test can fail gracefully.

At least now we have an actual failure:
```
  1) test.bulk_docs.js-http #2935 new_edits=false with single unauthorized:
     AssertionError: expected [] to have a length of 1 but got 0
      at tests/integration/test.bulk_docs.js:451:27
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by loic** [comment]
> express-pouchdb in the minimum mode is not a fully fledged CouchDB, but the function the test suite uses to check for that thinks it is
> Not sure what the easiest way to actually fix this is.

If the `pouchdb` test suite now requires some of those functionalities, maybe we should activate them by default in the `minimumForPouchDB` mode? Note that I tried adding `validation` (the reason `test.bulk_docs.js` actually fails) to the `modes.minimumForPouchDB` array but that didn't seem to work, I guess I'm missing other roles like routes, changing the mode in `express-pouchdb-minimum-for-pouchdb` to `fullCouchDB` worked however, and also addressed [all other failing tests](https://travis-ci.org/newlogic42/pouchdb-server/builds/328791881).

If we want to preserve backwards compatibility we could only change the test instance of `express-pouchdb`, but then we'd make the README lie a little: "minimumForPouchDB [...] This is the minimum required to make the PouchDB test suite run".

At least we are seeing the light at the end of the tunnel, we just need to turn my last commit into the preferred option, wdyt @marten-de-vries?

**Comment by loic** [comment]
The following works:

```
'use strict';

var PouchDB = require('pouchdb');

var app = require('../packages/node_modules/express-pouchdb')(PouchDB, {
  mode: 'minimumForPouchDB',
  overrideMode: {
    'include': [
      'routes/replicate',
      'validation'
    ]
  }
});
app.listen(6984);
```

I'm not sure about `validation`, but `routes/replicate` make sense to me to have as a default mode.

**Comment by marten-de-vries** [comment]
I think the proper fix would be to change [isCouchDB](https://github.com/pouchdb/pouchdb/blob/master/tests/integration/utils.js#L185) to something that instead detects what it is used for: whether validation is supported. Renaming the function would be a nice bonus. We should probably open an issue for that on the pouchdb repo.

But as that would take at least another release to be usable, I'm fine with whatever workaround you come up with for now. Including enabling a few extra includes.

**Comment by loic** [comment]
CI doesn't seem to pick up changes.

**Comment by loic** [comment]
The description of `minimumForPouchDB` is the following:

> 'minimumForPouchDB': just exposes parts of the HTTP API that map 1-1 to the PouchDB api. This is the minimum required to make the PouchDB test suite run, and a nice start when you just need an HTTP API to replicate with.

I went with the hybrid approach, I changed the `modes.minimumForPouchDB` mode to add the replications routes, since it seems to me it qualifies as `parts of the HTTP API that map 1-1 to the PouchDB api`, and I added `validation` to the test runner in the interim of a fix in the `pouchdb` test suite.

**Comment by marten-de-vries** [comment]
Actually, ``_replicate`` is not required for passive replication, only ``_revs_diff`` is. That test just uses APIs that were not meant to be used with pouchdb-express-router/[express-pouchdb in minimum mode]. It detects the first properly, but not the second using ``isCouchDB``.

Anyway, we can fix that later. I'm going to merge this.

**Comment by marten-de-vries** [comment]
Thanks for all your hard work on this, @loic!

**Comment by marten-de-vries** [comment]
That sounds like a great solution.

**Pull request merged**
