### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by loic**
Refs https://github.com/pouchdb/pouchdb-req-http-query/issues/18.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
One of the failed Travis tests might be fixed just by restarting, but the other seems to actually be caused by this PR: https://travis-ci.org/pouchdb/pouchdb-server/jobs/288523432

I think the problem is that we're pinning an old version of PouchDB: https://github.com/pouchdb/pouchdb-server/blob/master/bin/test-setup.sh. Hopefully solving the error is as 'easy' as upgrading the version, but it might also be it was pinned for a reason, no way to be sure without trying it.

**Comment by loic** [comment]
Interesting that the PouchDB pinning happens through the test script. If you just `npm install` the checked out monorepo you'll end up with PouchDB `^5.1.0` from the indirect dependency in `pouchdb-plugin-helper`.

We may have a bit of a catch 22 here because recent version of PouchDB (post https://github.com/pouchdb/pouchdb/pull/5398) are not compatible with `pouchdb-auth` due to the bug I fixed in https://github.com/pouchdb/pouchdb/pull/6793.

**Comment by marten-de-vries** [comment]
So as you fixed that regression, could we just pin pouchdb-server to use pouchdb's current master? It would not be the first time we had to do that for pouchdb-server, waiting for the pouchdb releases to catch up.

**Comment by loic** [comment]
My fix isn't merged yet, so we probably need to wait for that.

**Comment by marten-de-vries** [comment]
Right, I missed that. Thanks.

**Comment by loic** [comment]
@marten-de-vries correct me if I'm wrong, but it looks like https://github.com/pouchdb/pouchdb-server/blob/master/bin/test-setup.sh is only used for actually testing `pouchdb` (i.e. not `pouchdb-server`): https://github.com/pouchdb/pouchdb-server/blob/master/package.json#L6-L7. I'm not sure if it's a convenience alias used by developers or actually part of the `pouchdb-server` CI. `npm run unit-tests` and Travis seem to be testing against `pouchdb: ^5.1.0` which would explain that the incompatibilities with `pouchdb` 6+ didn't surface earlier.

**Comment by loic** [comment]
Closing this PR, as much more is needed to get a working CI, this branch is superseded by the branch tracked by https://github.com/newlogic42/pouchdb-server/pull/2.

**Comment by marten-de-vries** [comment]
Closing as per previous  comment

**Pull request closed without merging**
