### PR TITLE
(#131) - add --sqlite option

### PR DESCRIPTION
**Pull request by nolanlawson**
Tested manually, and this seems to be working. But just
to be prudent, I've added an extra Travis test.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
looks good, :+1:.

**Comment by nolanlawson** [comment]
Updated to use pouchdb@5.3.1 and to avoid the `prefix` hack. As long as it's still green, I'll merge and publish.

**Comment by nolanlawson** [comment]
PhantomJS seems perma-broken. I'm going to disable it and then open a new issue.

**Comment by nolanlawson** [comment]
03faee046b8b0d565bee8c62c0b80446f54b0211

**Pull request closed without merging**
