### PR TITLE
(pouchdb/pouchdb#4052) - Add Apache license

### PR DESCRIPTION
**Pull request by nolanlawson**
Need confirmation from @nick-thompson that he's cool with this,
because the old license was his personal one.

### CODE REVIEW

**Comment by nick-thompson** [comment]
Sure, I've no problem with this. Just curious, in #107 you mention that pouchdb-server is "supposed to be Apache 2" – why is that? Just to be consistent with PouchDB itself?

**Comment by nolanlawson** [comment]
Sorry for being vague; I mean because basically everything in the `pouchdb` org is Apache 2-licensed. I don't know that anyone has any strong feelings either way, but given that both CouchDB and PouchDB are Apache 2, it just seems to make sense.

**Comment by nick-thompson** [comment]
Yep, makes sense to me. Thanks for pinging me about the original license. And I'm glad to see this project is still alive and well!

**Comment by nolanlawson** [comment]
Oh yeah, @marten-de-vries has really taken it to another level. It's actually really close to feature parity with CouchDB 1.x by now. :)

**Pull request merged**
