### PR TITLE
finish up monorepo

### PR DESCRIPTION
**Pull request by gr2m**
finishes merging currently listed repos at #197

I think the separate pull requests run into issues because of cross references, so I try to solve them all at once here :)

closes #242, closes #244, closes #245, closes #248

### CODE REVIEW

**Comment by gr2m** [comment]
I can now reproduce the error with `npm run test-express-minimum` when testing in node 6.11.0 & npm 3.10.10.

The error here: https://travis-ci.org/pouchdb/pouchdb-server/jobs/250086626#L3465 comes from this assertion here: https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.all_docs.js#L752

when run with `npm run test-express-minimum`, then `_conflicts`  is an empty array `[]` instead of undefined. So that might be a pouchdb server error somewhere. But all the rest is passing, so I think this is good to go

**Comment by gr2m** [comment]
I’m positive that this is fixed in latest PouchDB 6. But upgrading to it (and testing with latest PouchDB test suite) is another rabbit hole :( 

I honestly don’t know what to do. I say we merge this in despite the failing tests. We continue to add all of the other modules that pouchdb-server depends on and merge it into the repo. Then we upgrade to latest POuchDB and fix all the incompatibilities, now that they are all in the mono repo.

I fear this is another 1-3 days of work, depending on how many other rabbit holes there are.

**Comment by gr2m** [comment]
These are the tests that are currently failing from the PouchDB Test suite at https://github.com/pouchdb/pouchdb/tree/f9beadd (which i think is the last commit before 6.2.0 release)

### test.bulk_docs

- '#2935 new_edits=false with single unauthorized'

### test.replication

- '#2268 dont stop replication if single forbidden'
- '#2268 dont stop replication if single unauth'
- '#2268 dont stop replication if many unauth'
- '#3171 Forbidden validate_doc_update error message'
- '#3171 Unauthorized validate_doc_update error message'
- '#3070 Doc IDs with validate_doc_update errors'
- '#3270 triggers "denied" events'

### test.sync

- '#3270 triggers "denied" events'
- '#3270 triggers "denied" events, reverse direction'

**Comment by garrensmith** [comment]
You can change the pouchdb test version used herer https://github.com/pouchdb/pouchdb-server/blob/master/bin/test-setup.sh#L18

But if you still struggling I guess lets merge and take it from there.

**Comment by marten-de-vries** [comment]
@loic: is this PR still useful as a base to get pouchdb-vhost, pouchdb-size and pouchdb-show merged after all the work you've done recently? Or can it be closed?

**Comment by loic** [comment]
I'm using it as inspiration but it doesn't need to remain open as I'm gonna open new ones.

**Comment by marten-de-vries** [comment]
Ok, then I'll close this PR and the ones it's based on.

**Pull request closed without merging**
