### PR TITLE
(#92) - Fix Travis

### PR DESCRIPTION
**Pull request by marten-de-vries**
(hopefully ;)

### CODE REVIEW

**Comment by yaronyg** [comment]
Don't mean to be silly but does this even require a +1?

**Comment by marten-de-vries** [comment]
@yaronyg On repo's that aren't pouchdb/pouchdb we sometimes just push if a PR stands unopposed after a few (say 3) days. pouchdb/pouchdb always needs a +1.

**Comment by yaronyg** [comment]
@marten-de-vries - Thanks for reminding me, @daleharvey had told me that but I forgot. I'm guessing however that it is 'polite' if one has actually looked at the commit to +1 anyway just so the commiter doesn't have to wait a few days? 

BTW, I'm asking these annoying questions because I'm new to the community and it's easier to ask and be slightly annoying than to do it wrong and seriously piss someone off. :)

**Comment by marten-de-vries** [comment]
@yaronyg It's no bother at all. To answer your question: yes, a +1 is always appreciated, I consider timebombing (pushing to master without a +1) pretty much a last resort.

**Comment by marten-de-vries** [comment]
Closing in favour of https://github.com/pouchdb/pouchdb/pull/3373.

@yaronyg This is a good example of why we review even small commits, there was an easier way available I didn't know about in this case.

**Pull request closed without merging**
